apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repo }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        args:
        - -c
        - /app/config/main.yaml
        ports:
        - name: metrics
          containerPort: {{ .Values.config.port }}
        - name: ws
          containerPort: {{ .Values.config.portWs }}         
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: {{ .Values.config.port }}
          initialDelaySeconds: 10
          timeoutSeconds: 200
        {{ if ne .Values.environment "ci" }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{ end }}
        volumeMounts:
        - name: config
          mountPath: /app/config 
        - name: secret-wallet
          mountPath: {{ dir .Values.config.registrar.keystore.walletFilePath }}
          readOnly: true
        - name: secret-password
          mountPath: {{ dir .Values.config.registrar.keystore.passwordFilePath }}
          readOnly: true      
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }} 
      - name: secret-wallet
        secret:
          secretName: {{ .Release.Name }}-wallet
          items:
          - key: registrar_wallet_json
            path: {{ base .Values.config.registrar.keystore.walletFilePath }} 
      - name: secret-password
        secret:
          secretName: {{ .Release.Name }}-password
          items:
          - key: registrar_password
            path: {{ base .Values.config.registrar.keystore.passwordFilePath }}              