apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-pod-restarter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-pod-restarter
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-pod-restarter