apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-wallet
type: Opaque
data:
  registrar_wallet_json: {{ .Values.secret.registrarWalletValue | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-password
type: Opaque
data:
  registrar_password: {{ .Values.secret.registrarPasswordValue | b64enc | quote }}  