endpoint: "wss://registrar-test-0.w3f.tech"
nodePort: 3000
challengerPort: 3001
logLevel: info
registrarIndex: 0

registrar:
  keystore:
    filePath: /Users/ale/Downloads/5GpmfR5PWHX3x1X6wsZhDdpN1F4UKUYPr6mgPZKqLiJRgp5q.json
    passwordFilePath: '/Users/ale/Downloads/password'