endpoint: "wss://registrar-test-0.w3f.tech"
port: 3000
portWs: 3001
logLevel: info
registrar:
  index: 0
  keystore:
    walletFilePath: /Users/ale/Downloads/5GpmfR5PWHX3x1X6wsZhDdpN1F4UKUYPr6mgPZKqLiJRgp5q.json
    passwordFilePath: '/Users/ale/Downloads/password'