apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
data:
  registrar_pk_json: {{ .Values.secret.registrarPKValue | b64enc | quote }}
  registrar_password: {{ .Values.secret.registrarPasswordValue | b64enc | quote }}