environments:
  production:
  ci:
  local:  

repositories:
- name: w3f
  url: https://w3f.github.io/helm-charts/

  
releases:

{{- if or (eq .Environment.Name "ci") (eq .Environment.Name "local") }} 
- name: registrar-watcher
  chart: ../charts/polkadot-registrar-watcher
  values:
  - ./config/registrar-watcher-values.yaml.gotmpl
{{- end }}

{{- if eq .Environment.Name "production" }}  
- name: kusama-registrar-watcher
  namespace: registrar-kusama 
  chart: w3f/polkadot-registrar-watcher
  version: v0.3.0
  values:
  - ./config/registrar-watcher-values.yaml.gotmpl
  - ./config/kusama/registrar-watcher-values.yaml.gotmpl  

- name: polkadot-registrar-watcher
  namespace: registrar-polkadot 
  chart: w3f/polkadot-registrar-watcher
  version: v0.3.0
  values:
  - ./config/registrar-watcher-values.yaml.gotmpl
  - ./config/polkadot/registrar-watcher-values.yaml.gotmpl  

- name: polkadot-registrar-watcher
  namespace: registrar-polkadot 
  chart: w3f/polkadot-registrar-watcher
  version: v0.3.0
  values:
  - ./config/registrar-watcher-values.yaml.gotmpl
  - ./config/registrar-test/registrar-watcher-values.yaml.gotmpl    
{{- end }}